-- MySQL Script generated by MySQL Workbench
-- 11/14/15 15:15:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vas` DEFAULT CHARACTER SET utf8;
USE `vas` ;

-- -----------------------------------------------------
-- Table `vas`.`人员`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vas`.`人员` (
  `人员编号` VARCHAR(45) NOT NULL,
  `人员姓名` VARCHAR(45) NOT NULL,
  `身份` VARCHAR(45) NOT NULL,
  `是否在职` TINYINT(1) NOT NULL,
  PRIMARY KEY (`人员编号`),
  UNIQUE INDEX `id人员_UNIQUE` (`人员编号` ASC))
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `vas`.`标准器材`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vas`.`标准器材` (
  `器材编号` VARCHAR(45) NOT NULL,
  `器材类型` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`器材编号`))
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `vas`.`样品`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vas`.`样品` (
  `样品编号` VARCHAR(45) NOT NULL,
  `生产厂家` VARCHAR(45) NOT NULL,
  `样品类型` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`样品编号`))
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `vas`.`温湿计数据`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vas`.`温湿计数据` (
  `检测人员编号` VARCHAR(45) NOT NULL,
  `标准器材编号` VARCHAR(45) NOT NULL,
  `样品编号` VARCHAR(45) NOT NULL,
  `标准温度` DOUBLE NOT NULL,
  `标准湿度` DOUBLE NOT NULL,
  `样品温度` DOUBLE NOT NULL,
  `样品湿度` DOUBLE NOT NULL,
  `检测时间` DATETIME NOT NULL,
  PRIMARY KEY (`检测人员编号`, `标准器材编号`, `样品编号`, `检测时间`),
  INDEX `标准器材编号_idx` (`标准器材编号` ASC),
  INDEX `样品编号_idx` (`样品编号` ASC),
  CONSTRAINT `温湿计_检测人员编号`
    FOREIGN KEY (`检测人员编号`)
    REFERENCES `vas`.`人员` (`人员编号`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `温湿计_标准器材编号`
    FOREIGN KEY (`标准器材编号`)
    REFERENCES `vas`.`标准器材` (`器材编号`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `温湿计_样品编号`
    FOREIGN KEY (`样品编号`)
    REFERENCES `vas`.`样品` (`样品编号`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;

-- -----------------------------------------------------
-- Table `vas`.`天平数据`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vas`.`天平数据` (
  `检测人员编号` VARCHAR(45) NOT NULL,
  `标准器材编号` VARCHAR(45) NOT NULL,
  `样品编号` VARCHAR(45) NOT NULL,
  `标准压力` DOUBLE NOT NULL,
  `样品压力` DOUBLE NOT NULL,
  `检测时间` DATETIME NOT NULL,
  PRIMARY KEY (`检测人员编号`, `标准器材编号`, `样品编号`, `检测时间`),
  INDEX `标准器材编号_idx` (`标准器材编号` ASC),
  INDEX `样品编号_idx` (`样品编号` ASC),
  CONSTRAINT `天平_检测人员编号`
    FOREIGN KEY (`检测人员编号`)
    REFERENCES `vas`.`人员` (`人员编号`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `天平_标准器材编号`
    FOREIGN KEY (`标准器材编号`)
    REFERENCES `vas`.`标准器材` (`器材编号`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `天平_样品编号`
    FOREIGN KEY (`样品编号`)
    REFERENCES `vas`.`样品` (`样品编号`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `vas`.`血压计数据`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vas`.`血压计数据` (
  `检测人员编号` VARCHAR(45) NOT NULL,
  `标准器材编号` VARCHAR(45) NOT NULL,
  `样品编号` VARCHAR(45) NOT NULL,
  `标准高压` INT NOT NULL,
  `标准低压` INT NOT NULL,
  `样品高压` INT NOT NULL,
  `样品低压` INT NOT NULL,
  `检测时间` DATETIME NOT NULL,
  PRIMARY KEY (`检测人员编号`, `标准器材编号`, `样品编号`, `检测时间`),
  INDEX `标准器材编号_idx` (`标准器材编号` ASC),
  INDEX `样品编号_idx` (`样品编号` ASC),
  CONSTRAINT `血压计_检测人员编号`
    FOREIGN KEY (`检测人员编号`)
    REFERENCES `vas`.`人员` (`人员编号`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `血压计_标准器材编号`
    FOREIGN KEY (`标准器材编号`)
    REFERENCES `vas`.`标准器材` (`器材编号`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `血压计_样品编号`
    FOREIGN KEY (`样品编号`)
    REFERENCES `vas`.`样品` (`样品编号`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
