-- MySQL Script generated by MySQL Workbench
-- 11/08/15 22:06:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Member` (
  `Memberid` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Position` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Memberid`),
  UNIQUE INDEX `Memberid_UNIQUE` (`Memberid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Material` (
  `Material_Id` VARCHAR(45) NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Factory` VARCHAR(45) NULL,
  `Date_pro` DATE NULL,
  `Lifetime` INT NULL,
  PRIMARY KEY (`Material_Id`),
  UNIQUE INDEX `Material_Id_UNIQUE` (`Material_Id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Xueya_Data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Xueya_Data` (
  `Date` DATETIME NOT NULL,
  `High` INT NOT NULL,
  `Down` INT NOT NULL,
  UNIQUE INDEX `Date_UNIQUE` (`Date` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Yali_Data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Yali_Data` (
  `Date` DATETIME NOT NULL,
  `Pull` DOUBLE NOT NULL,
  UNIQUE INDEX `idYali_Data_UNIQUE` (`Date` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Wenshi_Data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Wenshi_Data` (
  `Date` DATETIME NOT NULL,
  `Wendu` DOUBLE NOT NULL,
  `Shidu` DOUBLE NOT NULL,
  UNIQUE INDEX `Date_UNIQUE` (`Date` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
